# Generated by Django 3.1 on 2020-08-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_casetimelinesubject_casetimelinethread_castetimelinereaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetimelinesubject",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cases.case",
            ),
        ),
    ]
